---
- hosts: old
  vars:
    collect:
    - show int trunk
    - show int status
    - show ip dhcp snooping binding
    - show mac address-table
  tasks:

  - name: Store destination directory in variable
    set_fact:
      dest_dir: "{{ playbook_dir  | replace('ansible', '') }}/collect_state_old"

  - ios_command:
      commands: show ip vrf
    register: output

  - set_fact:
      vrf_list: "{{ output | ios_vrf_list }}"

  - ios_command:
      commands: "show ip arp vrf {{ item }}"
    loop: "{{ vrf_list }}"
    register: arp_result

  - copy:
      content: "{{arp_result.results[index].stdout_lines[0]|join('\n')}}"
      dest: "{{ dest_dir }}/{{ inventory_hostname }}_sh_ip_arp_vrf_{{ item }}.txt"
    delegate_to: localhost
    loop: "{{ vrf_list }}"
    loop_control:
      index_var: index

  - ios_command:
      commands: "{{ item }}"
    loop: "{{ collect }}"
    register: other_result

  - copy:
      content: "{{other_result.results[index].stdout_lines[0]|join('\n')}}"
      dest: "{{ dest_dir }}/{{inventory_hostname}}_sh_{{item|replace(' ','_')}}.txt"
    delegate_to: localhost
    loop: "{{ collect }}"
    loop_control:
      index_var: index
