---
- hosts: staging

  tasks:

  - name: Gather facts
    ios_facts:
      gather_subset: min
    register: output

  - name: Save hostname into variable
    set_fact:
      hostname: "{{ inventory_hostname }}"

  - name: Push AAA configs to staged switches
    cisco.ios.ios_config:
      src: "../lcm_configs_fixed/{{inventory_hostname}}-aaa.txt"
    when: hostname == output.ansible_facts.ansible_net_hostname
