---
- hosts: all
  tasks:

  - name: Store management IP address into variable
    set_fact:
      mgmt_ip_var: "{{hostvars[inventory_hostname]['ansible_host']}}"

  - name: Query IP interface table
    ansible.netcommon.cli_parse:
      command: "show ip int brief"
      parser:
        name: ansible.netcommon.ntc_templates
    register: raw_ip_intf_table

  - name: Store parsed IP interface table into dict
    set_fact:
      ip_intf_table: "{{ ip_intf_table | default( {'result': raw_ip_intf_table['parsed']} ) }}"

  - name: Query management interface from parsed data
    set_fact:
      result: "{{ ip_intf_table | json_query(query) }}"
    vars:
      query: "result[?ipaddr=='{{mgmt_ip_var}}'].intf"

  - debug: var=result

  - name: Query VTY config
    ios_command:
      commands: 
      - "show run | s line vty"
    register: output

  - debug: var=output

  - name: Find name of VTY ACL, if any
    set_fact:
      vty_acl_line: "{{ output.stdout[0] | regex_search('access-class .*', multiline=True) }}"
      vty_acl_name: "{{ output.stdout[0] | regex_search('access-class ([A-Za-z-_]+)', '\\1', multiline=True) }}"

  - debug: var=vty_acl_line

  - debug: var=vty_acl_name

