---
- hosts: all
  tasks:

  - name: Get current directory
    set_fact:
      curr_dir: "{{ playbook_dir }}"

  - name: Gather Facts
    ios_facts:
      gather_subset: all
    register: output

  - name: Store config from device into list
    set_fact:
      configuration: "{{ output.ansible_facts.ansible_net_config.splitlines() }}"

  - name: Register management IP address
    set_fact:
      mgmt_ip: "{{ output.ansible_facts.ansible_net_interfaces.Vlan99.ipv4[0].address }}"

  - name: Register discovered hostname
    set_fact:
      discovered_hostname: "{{ output.ansible_facts.ansible_net_hostname }}"

  - name: Determine based on 'service compresss-config' line if switch is already been loaded with preconfig or not
    set_fact:
      staging_config_state: "{{hostvars[inventory_hostname]['configuration'] | select('match', 'service compress-config') | list | first | default('new_switch')}}"

  - name: Delete content of configs directory
    shell: rm -f "{{curr_dir}}/configs/*"
    delegate_to: localhost
    run_once: true

  - name: Create host entries for hosts file
    template: "src=./templates/lcm-dynamic_inventory.j2 dest=./configs/{{inventory_hostname}}.lcm"
    check_mode: no

  - name: Generate staging LCM inventory file
    assemble:
      src: ./configs/
      regexp: '.*lcm'
      dest: ./hosts
    delegate_to: localhost
    run_once: true

  - meta: refresh_inventory
